language: python
dist: xenial

cache: pip

os:
  - linux

env:
  - PYVER=2.7 NPY="numpy==1.13.1"
  - PYVER=2.7 NPY="numpy==1.14.5"
  - PYVER=2.7 NPY="numpy>=1.15"

  - PYVER=3.5 NPY="numpy==1.13.1"
  - PYVER=3.5 NPY="numpy==1.14.5"
  - PYVER=3.5 NPY="numpy>=1.15"

  - PYVER=3.6 NPY="numpy==1.13.1"
  - PYVER=3.6 NPY="numpy==1.14.5"
  - PYVER=3.6 NPY="numpy>=1.15"

  - PYVER=3.7 NPY="numpy==1.14.5"
  - PYVER=3.7 NPY="numpy>=1.15"

  - PYVER=3.8 NPY="numpy>=1.15"

  - PYVER=pypy2.7 NPY="numpy>=1.15"

  - PYVER=pypy3.6 NPY="numpy>=1.15"

install:
  # Install conda
  - wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --add channels conda-forge;
  # conda install --quiet --yes -c conda-forge/label/mamba-alpha mamba
  - conda config --set always_yes yes --set changeps1 no
  # Create the conda testing environment
  # FIXME: Mamba decides to upgrade Python here so pin it again
  # FIXME: Channel priority is also mixed up
  # FIXME: Mamba doesn't install pip by default
  # FIXME: Mamba causes pip install numpy to be extremely slow
  - if [[ "${PYVER}" = pypy* ]]; then
      conda create --quiet --yes -n testenv ${PYVER};
    elif [ "${PYVER}" = "2.7" ] || [ "${PYVER}" = "3.6" ] || [ "${PYVER}" = "3.7"] || [ "${PYVER}" = "3.8" ]; then
      conda create --quiet --yes -n testenv python=${PYVER} pip;
    else
      conda create --quiet --yes -n testenv python=${PYVER};
    fi
  - source activate testenv
  - if [ "${PYVER}" = "2.7" ] || [ "${PYVER}" = "3.6" ] || [ "${PYVER}" = "3.7"] || [ "${PYVER}" = "3.8" ]; then
      conda install --quiet --yes python=${PYVER} pip root;
      source activate testenv;
    fi
  - pip install --upgrade setuptools-scm
  - pip install $NPY
  - python -c 'import numpy; print(numpy.__version__)'
  - pip install pytest-error-for-skips

addons:
  apt:
    packages:
      - python-setuptools

script:
  if [ "${PYVER}" = "2.7" ] || [ "${PYVER}" = "3.6" ] || [ "${PYVER}" = "3.7" ] || [ "${PYVER}" = "3.8" ]; then
    pytest --error-for-skips -v tests;
  else
    pytest -v tests;
  fi